{% set name = "rlpycairo" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rlPyCairo-{{ version }}.tar.gz
  sha256: 7cd1eac30fe69d98f75d67a54892f9c10534a047b9a959ef17bb3926a196e50a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.7
    - pycairo >=1.20.0
    - freetype-py >=2.3

test:
  imports:
    - rlPyCairo
    - rlPyCairo.gstate
    - rlPyCairo.pil2pict
  commands:
    - pip check
  requires:
    - pip
    - reportlab

about:
  home: https://hg.reportlab.com/hg-public/rlPyCairo
  summary: Plugin backend renderer for reportlab.graphics.renderPM
  description: |
    This is a plugin for the ReportLab PDF Toolkit.
    which constructs rich PDF documents, and also creation
    of charts in a variety of bitmap and vector formats.

    This plugin is intended to replace most of the usage of the
    libart based C extension _renderPM which has been shown to
    have issues when rendering complex documents.

    This backend can be brought into use by setting
    reportlab.rl_config.renderPMBackend = 'rlPyCairo'
    any of the methods detailed in reportlab/rl_config.py
    can be used to accomplish this.

    The new backend seems able to handle all the same behaviour as
    _renderPM and the only place where it seems inferior is in the
    rendering of scaled images and the speed with which it draws
    text.

    At present the rlPyCairo backend only uses the _renderPM extension
    to use its mapping of ReportLab font names to extract paths for
    rendering this is no doubt the reason for its slowness when
    rendering text.

    Currently we are not making use of any of the more advanced
    abilities of PyCairo such as transparency, patterns etc,
    but that may change in the future.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bkpoon
